// Copyright 2026, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package logs

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/crypto/nacl/box"
)

var testPublicKey = [32]byte{
	0x7a, 0x1b, 0x9e, 0x4f, 0x2c, 0x8d, 0x3a, 0x5b,
	0x6e, 0x0f, 0x1d, 0x4c, 0x7b, 0x8a, 0x9e, 0x2f,
	0x3d, 0x5c, 0x6b, 0x0a, 0x1e, 0x4d, 0x7c, 0x8b,
	0x9f, 0x2e, 0x3c, 0x5d, 0x6a, 0x0b, 0x1f, 0x4e,
}

func init() {
	fetchPulumiPublicKey = func(_ context.Context) ([32]byte, string, error) {
		return testPublicKey, "mock-test-key", nil
	}
}

func TestSealedBoxEncrypterRoundTrip(t *testing.T) {
	t.Parallel()

	pub, priv, err := box.GenerateKey(rand.Reader)
	require.NoError(t, err)

	enc := &sealedBoxEncrypter{publicKey: *pub, keyID: "test-key-42"}
	ctx := t.Context()

	plaintext := "dGhpcyBpcyBhIHNlc3Npb24ga2V5" // base64-encoded session key
	ciphertext, err := enc.EncryptValue(ctx, plaintext)
	require.NoError(t, err)

	// Verify the format: "sealed-box:<keyID>:<base64>"
	assert.True(t, strings.HasPrefix(ciphertext, "sealed-box:test-key-42:"))

	// Extract and decrypt the sealed box.
	parts := strings.SplitN(ciphertext, ":", 3)
	require.Len(t, parts, 3)
	assert.Equal(t, "sealed-box", parts[0])
	assert.Equal(t, "test-key-42", parts[1])

	sealed, err := base64.StdEncoding.DecodeString(parts[2])
	require.NoError(t, err)

	decrypted, ok := box.OpenAnonymous(nil, sealed, pub, priv)
	require.True(t, ok, "sealed box decryption failed")
	assert.Equal(t, plaintext, string(decrypted))
}

func TestSealedBoxEncrypterKeyIDEmbedded(t *testing.T) {
	t.Parallel()

	pub, _, err := box.GenerateKey(rand.Reader)
	require.NoError(t, err)

	enc := &sealedBoxEncrypter{publicKey: *pub, keyID: "rotation-key-99"}
	ctx := t.Context()

	ciphertext, err := enc.EncryptValue(ctx, "test")
	require.NoError(t, err)

	assert.True(t, strings.HasPrefix(ciphertext, "sealed-box:rotation-key-99:"))
}

func TestSealedBoxEncrypterDifferentCiphertexts(t *testing.T) {
	t.Parallel()

	// Each encryption should produce different ciphertext due to the
	// ephemeral key pair generated by SealAnonymous.
	pub, _, err := box.GenerateKey(rand.Reader)
	require.NoError(t, err)

	enc := &sealedBoxEncrypter{publicKey: *pub, keyID: "key"}
	ctx := t.Context()

	ct1, err := enc.EncryptValue(ctx, "same-input")
	require.NoError(t, err)
	ct2, err := enc.EncryptValue(ctx, "same-input")
	require.NoError(t, err)

	assert.NotEqual(t, ct1, ct2)
}

func TestShareGzipLogIntegration(t *testing.T) {
	t.Parallel()

	e := newTestEnv(t)

	content := "I 12:00:00.000000 test log line for sharing\n"
	writeGzipFile(t, e, "test-20260401T120000.log", content)

	stdout, _ := e.RunCommand("pulumi", "logs", "share",
		filepath.Join(e.RootPath, "test-20260401T120000.log"))
	_ = stdout

	// The shared file should exist and be a PLOG file.
	shared := filepath.Join(e.RootPath, "test-20260401T120000.shared.log")
	assertFileHasPrefix(t, shared, "PLOG")

	// The original plaintext should not appear in the shared file.
	assertFileDoesNotContain(t, shared, "test log line for sharing")
}

func TestShareEncryptedLogIntegration(t *testing.T) {
	t.Parallel()

	e := newTestEnv(t)
	e.Env = append(e.Env, "PULUMI_ENABLE_AUTOMATIC_LOGGING=true")

	e.RunCommand("pulumi", "login", "--cloud-url", e.LocalURL())
	e.WriteTestFile("Pulumi.yaml", `name: test-share
runtime: nodejs`)
	e.RunCommand("pulumi", "stack", "init", "dev")
	e.RunCommandExpectError("pulumi", "preview")

	logFile := findLogInDir(t, e.HomePath)
	e.RunCommand("pulumi", "logs", "share", logFile)

	shared := strings.TrimSuffix(logFile, ".log") + ".shared.log"
	assertFileHasPrefix(t, shared, "PLOG")
}
